# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'showboat.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QPixmap, QIcon
from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *
import requests
import urllib
import pprint


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):

        self.API_KEY = "eb8c4f6c9f1273bade165918d7be55d5"

        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(1067, 693)
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabs = QtWidgets.QTabWidget(self.centralwidget)
        self.tabs.setGeometry(QtCore.QRect(10, 0, 1051, 641))
        self.tabs.setObjectName("tabs")
        self.homeTab = QtWidgets.QWidget()
        self.homeTab.setObjectName("homeTab")
        self.bandPhotoLabel = QtWidgets.QLabel(self.homeTab)
        self.bandPhotoLabel.setGeometry(QtCore.QRect(20, 20, 401, 291))
        self.bandPhotoLabel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.bandPhotoLabel.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.bandPhotoLabel.setLineWidth(3)
        self.bandPhotoLabel.setText("")
        self.bandPhotoLabel.setObjectName("bandPhotoLabel")
        sizePolicy = QSizePolicy(QSizePolicy.Ignored, QSizePolicy.Ignored)
        self.bandBioHeader = QtWidgets.QLabel(self.homeTab)
        self.bandBioHeader.setGeometry(QtCore.QRect(250, 330, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(19)
        self.bandBioHeader.setFont(font)
        self.bandBioHeader.setObjectName("bandBioHeader")
        self.bandBioLabel = QtWidgets.QLabel(self.homeTab)
        self.bandBioLabel.setWordWrap(True)
        self.bandBioLabel.setGeometry(QtCore.QRect(20, 380, 591, 221))
        font = QtGui.QFont()
        font.setFamily("Impact")
        self.bandBioLabel.setFont(font)
        self.bandBioLabel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.bandBioLabel.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.bandBioLabel.setLineWidth(3)
        self.bandBioLabel.setText("")
        self.bandBioLabel.setObjectName("bandBioLabel")
        self.bandInfoNameLabel = QtWidgets.QLabel(self.homeTab)
        self.bandInfoNameLabel.setGeometry(QtCore.QRect(430, 20, 181, 81))
        font = QtGui.QFont()
        font.setFamily("Impact")
        self.bandInfoNameLabel.setFont(font)
        self.bandInfoNameLabel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.bandInfoNameLabel.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.bandInfoNameLabel.setLineWidth(3)
        self.bandInfoNameLabel.setText("")
        self.bandInfoNameLabel.setObjectName("bandInfoNameLabel")
        self.bandInfoOtherLabel = QtWidgets.QLabel(self.homeTab)
        self.bandInfoOtherLabel.setGeometry(QtCore.QRect(430, 120, 181, 91))
        font = QtGui.QFont()
        font.setFamily("Impact")
        self.bandInfoOtherLabel.setFont(font)
        self.bandInfoOtherLabel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.bandInfoOtherLabel.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.bandInfoOtherLabel.setLineWidth(3)
        self.bandInfoOtherLabel.setText("")
        self.bandInfoOtherLabel.setObjectName("bandInfoOtherLabel")
        self.bandInfoWebsiteLabel = QtWidgets.QLabel(self.homeTab)
        self.bandInfoWebsiteLabel.setGeometry(QtCore.QRect(430, 220, 181, 91))
        font = QtGui.QFont()
        font.setFamily("Impact")
        self.bandInfoWebsiteLabel.setFont(font)
        self.bandInfoWebsiteLabel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.bandInfoWebsiteLabel.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.bandInfoWebsiteLabel.setLineWidth(3)
        self.bandInfoWebsiteLabel.setText("")
        self.bandInfoWebsiteLabel.setObjectName("bandInfoWebsiteLabel")
        self.bandBioHeader_2 = QtWidgets.QLabel(self.homeTab)
        self.bandBioHeader_2.setGeometry(QtCore.QRect(670, 30, 291, 41))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(24)
        self.bandBioHeader_2.setFont(font)
        self.bandBioHeader_2.setAlignment(QtCore.Qt.AlignCenter)
        self.bandBioHeader_2.setObjectName("bandBioHeader_2")
        self.bandSearchLineEdit = QtWidgets.QLineEdit(self.homeTab)
        self.bandSearchLineEdit.setGeometry(QtCore.QRect(632, 89, 391, 41))
        self.bandSearchLineEdit.setObjectName("bandSearchLineEdit")
        self.lastSearchButton = QtWidgets.QPushButton(self.homeTab, clicked = lambda: self.get_lastfm_token())
        self.lastSearchButton.setGeometry(QtCore.QRect(650, 150, 161, 51))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(12)
        self.lastSearchButton.setFont(font)
        self.lastSearchButton.setObjectName("lastSearchButton")
        self.searchButton = QtWidgets.QPushButton(self.homeTab, clicked = lambda: self.artist_search())
        self.searchButton.setGeometry(QtCore.QRect(840, 150, 161, 51))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(12)
        self.searchButton.setFont(font)
        self.searchButton.setObjectName("searchButton")
        self.tourDatesHomeHeader = QtWidgets.QLabel(self.homeTab)
        self.tourDatesHomeHeader.setGeometry(QtCore.QRect(650, 230, 351, 41))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(19)
        self.tourDatesHomeHeader.setFont(font)
        self.tourDatesHomeHeader.setAlignment(QtCore.Qt.AlignCenter)
        self.tourDatesHomeHeader.setObjectName("tourDatesHomeHeader")
        self.tourDatesHomeList = QtWidgets.QListWidget(self.homeTab)
        self.tourDatesHomeList.setGeometry(QtCore.QRect(630, 290, 391, 311))
        self.tourDatesHomeList.setObjectName("tourDatesHomeList")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../Pictures/IconImages/icons/home.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabs.addTab(self.homeTab, icon, "")
        self.tourDatesTab = QtWidgets.QWidget()
        self.tourDatesTab.setObjectName("tourDatesTab")
        self.tabs.addTab(self.tourDatesTab, "")
        self.mapTab = QtWidgets.QWidget()
        self.mapTab.setObjectName("mapTab")
        self.tabs.addTab(self.mapTab, "")
        self.videoTab = QtWidgets.QWidget()
        self.videoTab.setObjectName("videoTab")
        self.tabs.addTab(self.videoTab, "")
        self.infoTab = QtWidgets.QWidget()
        self.infoTab.setObjectName("infoTab")
        self.tabs.addTab(self.infoTab, "")
        mainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(mainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1067, 23))
        self.menubar.setObjectName("menubar")
        mainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(mainWindow)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(mainWindow)
        self.tabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    # FUNCTIONS

    def add_it(self):
        response = requests.get('http://127.0.0.1:5000/test')
        band = response.json()["band"]
        self.tourDatesHomeList.addItem(band)
        self.bandSearchLineEdit.setText("")

    def get_photo(self):
        response = requests.get('http://127.0.0.1:5000/band-photo')
        img_url = response.json()["url"]
        data = urllib.request.urlopen(img_url).read()
        pixmap = QPixmap()
        pixmap.loadFromData(data)
        self.bandPhotoLabel.setPixmap(pixmap)
        self.bandPhotoLabel.setScaledContents(True)

    def artist_search(self):
        search_string = urllib.parse.quote(self.bandSearchLineEdit.text())
        # url = f"https://api.spotify.com/v1/search?q=artist%3A{search_string}&type=artist"
        # headers = {
        #     "Accept": "application/json",
        #     "Content-Type": "application/json",
        #     "Authorization": "Bearer BQD0MtwAM3RNohVy8G61SlaqJt7LfT0L-z7Z2g566kwGXt-YaZoYMPl2w3cqyStytxRhbAF5cKNjHLF3nMni91IzQR0EIh6hgSn30e0xzoVdvF50vDcpeDsKt3jJaF0xDNNq8oYIqCo3rf8"
        # }
        # response = requests.get(url, headers=headers)
        # pprint.pprint(response.json())
        # id = response.json()["artists"]["items"][0]["id"]
        # name = response.json()["artists"]["items"][0]["name"]
        # img_url = response.json()["artists"]["items"][0]["images"][0]["url"]

        bio = self.get_artist_bio(search_string)
        self.load_artist_bio(bio)
        # name = self.get_artist_name(search_string)
        # self.load_photo(img_url)
        # self.load_artist_name(name)

    def load_photo(self, img_url):
        data = urllib.request.urlopen(img_url).read()
        pixmap = QPixmap()
        pixmap.loadFromData(data)
        self.bandPhotoLabel.setPixmap(pixmap)
        self.bandPhotoLabel.setScaledContents(True)

    def load_artist_name(self, name):
        self.bandInfoNameLabel.setText(name)

    def load_artist_bio(self, bio):
        self.bandBioLabel.setText(bio)

    def get_artist_name(self, search_string):
        url = f"http://ws.audioscrobbler.com/2.0/?method=artist.getinfo&artist={search_string}&api_key={self.API_KEY}&format=json"
        response = requests.get(url)
        name = response.json()
        print("---------------NAME----------------")
        pprint.pprint(name)
        return name

    def get_artist_bio(self, search_string):
        url = f"http://ws.audioscrobbler.com/2.0/?method=artist.getinfo&artist={search_string}&api_key={self.API_KEY}&format=json"
        response = requests.get(url)
        pprint.pprint(response.json())
        bio = response.json()["artist"]["bio"]["summary"]
        print("---------------BIO----------------")
        pprint.pprint(bio)
        return bio


    # def get_lastfm_token(self):
    #     url = f"http://ws.audioscrobbler.com/2.0/?method=auth.gettoken&api_key={self.API_KEY}&format=json"
    #     response = requests.get(url)
    #     token = response.json()["token"]
    #     print(token)
    #     self.lastfm_user_auth(token)

    # def lastfm_user_auth(self, token):
    #     url = f"http://www.last.fm/api/auth/?api_key={self.API_KEY}&token={token}"
    #     requests.get(url)

        

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "ShowBoat"))
        self.bandBioHeader.setText(_translate("mainWindow", "Band Bio:"))
        self.bandBioHeader_2.setText(_translate("mainWindow", "Band Search:"))
        self.lastSearchButton.setText(_translate("mainWindow", "Last Search"))
        self.searchButton.setText(_translate("mainWindow", "Search Band"))
        self.tourDatesHomeHeader.setText(_translate("mainWindow", "Upcoming Tour Dates"))
        self.tabs.setTabText(self.tabs.indexOf(self.homeTab), _translate("mainWindow", "Home"))
        self.tabs.setTabText(self.tabs.indexOf(self.tourDatesTab), _translate("mainWindow", "Tour Dates"))
        self.tabs.setTabText(self.tabs.indexOf(self.mapTab), _translate("mainWindow", "Map"))
        self.tabs.setTabText(self.tabs.indexOf(self.videoTab), _translate("mainWindow", "Video"))
        self.tabs.setTabText(self.tabs.indexOf(self.infoTab), _translate("mainWindow", "Info"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mainWindow = QtWidgets.QMainWindow()
    ui = Ui_mainWindow()
    ui.setupUi(mainWindow)
    mainWindow.show()
    sys.exit(app.exec_())
